// generated by AI to see how a tb file would look like

`timescale 1ns/1ps

module alu_tb;

    import rv32i_pkg::*;

    logic [31:0] a;
    logic [31:0] b;
    aluop        alucontrol;
    logic [31:0] result;

    int tests_run;
    int tests_failed;

    // DUT
    alu dut (
        .a          (a),
        .b          (b),
        .alucontrol (alucontrol),
        .result     (result)
    );


    // ------------------------------------------------------------
    // Test helper
    // ------------------------------------------------------------
    task automatic check(
        input aluop        op,
        input logic [31:0] test_a,
        input logic [31:0] test_b,
        input logic [31:0] expected,
        input string       test_name
    );
        begin
            a          = test_a;
            b          = test_b;
            alucontrol = op;

            #1;  // Allow combinational logic to settle

            tests_run++;

            if (result !== expected) begin
                tests_failed++;

                $error(
                    "%s FAILED: a=%h b=%h expected=%h result=%h",
                    test_name,
                    test_a,
                    test_b,
                    expected,
                    result
                );
            end
            else begin
                $display(
                    "%s PASSED: a=%h b=%h result=%h",
                    test_name,
                    test_a,
                    test_b,
                    result
                );
            end
        end
    endtask


    // ------------------------------------------------------------
    // Tests
    // ------------------------------------------------------------
    initial begin

        tests_run    = 0;
        tests_failed = 0;

        $display("========================================");
        $display("            ALU TESTBENCH");
        $display("========================================");


        // ========================================================
        // ADD
        // ========================================================
        check(ALU_ADD, 32'd5,         32'd7,
                       32'd12,        "ADD normal");

        check(ALU_ADD, 32'd0,         32'd0,
                       32'd0,         "ADD zero");

        check(ALU_ADD, 32'hFFFF_FFFF, 32'd1,
                       32'h0000_0000, "ADD overflow");

        check(ALU_ADD, 32'h7FFF_FFFF, 32'd1,
                       32'h8000_0000, "ADD signed overflow");


        // ========================================================
        // SUB
        // ========================================================
        check(ALU_SUB, 32'd10,        32'd3,
                       32'd7,         "SUB normal");

        check(ALU_SUB, 32'd5,         32'd5,
                       32'd0,         "SUB equal");

        check(ALU_SUB, 32'd0,         32'd1,
                       32'hFFFF_FFFF, "SUB underflow");

        check(ALU_SUB, 32'h8000_0000, 32'd1,
                       32'h7FFF_FFFF, "SUB signed overflow");


        // ========================================================
        // AND
        // ========================================================
        check(ALU_AND, 32'hFFFF_0000, 32'h0F0F_0F0F,
                       32'h0F0F_0000, "AND pattern");

        check(ALU_AND, 32'hFFFF_FFFF, 32'h0000_0000,
                       32'h0000_0000, "AND zero");


        // ========================================================
        // OR
        // ========================================================
        check(ALU_OR,  32'hF0F0_0000, 32'h0000_0F0F,
                       32'hF0F0_0F0F, "OR pattern");

        check(ALU_OR,  32'h1234_5678, 32'h0000_0000,
                       32'h1234_5678, "OR zero");


        // ========================================================
        // XOR
        // ========================================================
        check(ALU_XOR, 32'hFFFF_0000, 32'h0F0F_0F0F,
                       32'hF0F0_0F0F, "XOR pattern");

        check(ALU_XOR, 32'hAAAA_AAAA, 32'hAAAA_AAAA,
                       32'h0000_0000, "XOR same");


        // ========================================================
        // SLL
        //
        // RV32I uses only b[4:0] as the shift amount.
        // ========================================================
        check(ALU_SLL, 32'h0000_0001, 32'd1,
                       32'h0000_0002, "SLL by 1");

        check(ALU_SLL, 32'h0000_0001, 32'd31,
                       32'h8000_0000, "SLL by 31");

        check(ALU_SLL, 32'h1234_5678, 32'd0,
                       32'h1234_5678, "SLL by 0");

        // 32 -> b[4:0] = 0
        check(ALU_SLL, 32'h1234_5678, 32'd32,
                       32'h1234_5678, "SLL shift mask");


        // ========================================================
        // SRL
        // ========================================================
        check(ALU_SRL, 32'h8000_0000, 32'd1,
                       32'h4000_0000, "SRL by 1");

        check(ALU_SRL, 32'h8000_0000, 32'd31,
                       32'h0000_0001, "SRL by 31");

        check(ALU_SRL, 32'h1234_5678, 32'd0,
                       32'h1234_5678, "SRL by 0");


        // ========================================================
        // SRA
        //
        // Arithmetic shift must preserve the sign bit.
        // ========================================================
        check(ALU_SRA, 32'h8000_0000, 32'd1,
                       32'hC000_0000, "SRA negative by 1");

        check(ALU_SRA, 32'h8000_0000, 32'd31,
                       32'hFFFF_FFFF, "SRA negative by 31");

        check(ALU_SRA, 32'h4000_0000, 32'd1,
                       32'h2000_0000, "SRA positive");

        check(ALU_SRA, 32'hFFFF_FFF8, 32'd2,
                       32'hFFFF_FFFE, "SRA -8 by 2");


        // ========================================================
        // SLT -- SIGNED comparison
        // ========================================================
        check(ALU_SLT, 32'd5,         32'd10,
                       32'd1,         "SLT positive true");

        check(ALU_SLT, 32'd10,        32'd5,
                       32'd0,         "SLT positive false");

        check(ALU_SLT, 32'd5,         32'd5,
                       32'd0,         "SLT equal");

        // -1 < 1
        check(ALU_SLT, 32'hFFFF_FFFF, 32'd1,
                       32'd1,         "SLT negative vs positive");

        // 1 < -1 is false
        check(ALU_SLT, 32'd1,         32'hFFFF_FFFF,
                       32'd0,         "SLT positive vs negative");

        // INT_MIN < INT_MAX
        check(ALU_SLT, 32'h8000_0000, 32'h7FFF_FFFF,
                       32'd1,         "SLT signed extremes");


        // ========================================================
        // SLTU -- UNSIGNED comparison
        // ========================================================
        check(ALU_SLTU, 32'd5,         32'd10,
                        32'd1,         "SLTU true");

        check(ALU_SLTU, 32'd10,        32'd5,
                        32'd0,         "SLTU false");

        check(ALU_SLTU, 32'd5,         32'd5,
                        32'd0,         "SLTU equal");

        // 0xFFFFFFFF = 4294967295 unsigned
        check(ALU_SLTU, 32'hFFFF_FFFF, 32'd1,
                        32'd0,         "SLTU max vs 1");

        check(ALU_SLTU, 32'd1,         32'hFFFF_FFFF,
                        32'd1,         "SLTU 1 vs max");

        check(ALU_SLTU, 32'h8000_0000, 32'h7FFF_FFFF,
                        32'd0,         "SLTU unsigned extremes");


        // ========================================================
        // Summary
        // ========================================================
        $display("");
        $display("========================================");
        $display("              TEST SUMMARY");
        $display("========================================");
        $display("Tests run    : %0d", tests_run);
        $display("Tests passed : %0d", tests_run - tests_failed);
        $display("Tests failed : %0d", tests_failed);

        if (tests_failed == 0) begin
            $display("");
            $display("ALL ALU TESTS PASSED");
        end
        else begin
            $display("");
            $fatal(1, "ALU TESTBENCH FAILED");
        end

        $display("========================================");

        $finish;
    end

endmodule